# Generated by Django 5.1.6 on 2025-02-18 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_rate', '0002_initial'),
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_rate_data', to='patients.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='HeartRate',
        ),
    ]
